SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `Projetomvc` ;

CREATE SCHEMA IF NOT EXISTS `Projetomvc` ;
USE `Projetomvc` ;

DROP TABLE IF EXISTS `lojinhaonline`.`produto` ;

CREATE TABLE IF NOT EXISTS `projetomvc`.`produto` (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) NULL,
  valorUnitario double,
  tipoUnidade varchar(20),
  qtdEstoque int,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

insert into produto(nome, valorUnitario, tipoUnidade, qtdEstoque) values("leite", 15.00, "litro", 5);
select * from produto;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
